ansible_host: ENC[AES256_GCM,data:Xep4hWCJQVK3Pcw=,iv:slJCoMQYev1cZW8JkSqRcvBsyF+R9rS8QpA+SEcgvw8=,tag:vUfKEB8Ke5rc6CQsTxeWpA==,type:str]
ansible_user: ENC[AES256_GCM,data:18KrWb8=,iv:BFQU+r/OHdSte+25PQkCT9CFAvo7q9YRCv50cxqfJeI=,tag:CcNwd6M77tWhXjwNfjY8xA==,type:str]
node_agent_obs_host: ENC[AES256_GCM,data:wqHCGEtyLgk=,iv:SYfkLv2idpbuAoXKi6MrT1cP4QuoDZ482/+yV4Txrc8=,tag:fFdpOolbM3o5Ljdhs+mRiA==,type:str]
node_agent_dockhand_url: ENC[AES256_GCM,data:CFA83OpJwg/IsewCI46ssY598wQ=,iv:WsAxi386HKWzKZoj/o1kqC0u0RQJJA3HtZzUU3mqEb0=,tag:gJje0aCHIx0c+0J4Y8CHwQ==,type:str]
node_agent_dockhand_token: ENC[AES256_GCM,data:pLdKiQwI5Bw=,iv:qGO1MwLW6+jJ0Dq/2JxZjjlNGhsYhTIQPxm+AFmo4QM=,tag:+Uc4FT2LwyfSysI9Xb2srw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXY29SZERVUHE1QVBEcVln
            VlZVdmVlTDVLQWNVUVUzekdHeVV1K0RVd2x3Cm15QTVDNStuR1Q1ajhKV0svYTVF
            R3h1WHFtak1iWlR3eVBoNWphOFg5NTgKLS0tIGhxK1F6YXh3MkYxeXJsWDBGeEE0
            VmM3WkxoeFZhVEVyandnbXlmdUVXZjgKqzd1j3VnJVAUZr2at6dO8ODc7qqpv8DV
            ceZulkn92nMOjKMzH8Ec3aP1XICtHAIZSr75uKNpSIBlip3LUN3aNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-23T08:47:52Z"
    mac: ENC[AES256_GCM,data:7WQbTtnEP2XqrXww8/e1lovp0YU2AohkMIFaw/3mBdBq4HkVVTl5lgiWM/Q6ifgU6pCMCc7PB5h2VuGqwImHHf/PHgyyHZJZ8Rk9feOq734wtiSaL2VNmaVIWLPg6s/bKS49yX47FC5mq8l7iWjwyH9pqAfMIA+WNu9gBH1d0NQ=,iv:qZpQW3rHIPwQxOL5gQhG7A5BEWBcznuj9yHMQuXfFWs=,tag:YtPfS7RPFUZVUw/bOtYj0A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
