ansible_host: ENC[AES256_GCM,data:lrawkk8N+To6K6E=,iv:dLjZ3ESRnb5f+TUR4i4GD+p06d8gzW1YqVsfz0vWQUw=,tag:4S3B506rRlLrlcJMJWY6Qw==,type:str]
ansible_user: ENC[AES256_GCM,data:cP6hq0Y=,iv:zLltfGGrCCZV2M9ccswdiIKvzz3DpB/BQf0fwYwTFNE=,tag:hGWK20y89qP+KY/25X9itg==,type:str]
node_agent_obs_host: ENC[AES256_GCM,data:6jOvudo1Q4U=,iv:IcrjFrcY7N3vqRNpGphpq5YNtlnW4oSQpZPMvF2bdXg=,tag:qU8Th3Tiyu4/x1uSzPViLQ==,type:str]
node_agent_dockhand_url: ENC[AES256_GCM,data:jIBRmn/6NEHrzW6nhm62N37b6D4=,iv:jtQxK/RUAmxj0I22y5yZ3TNgp5r/hr9V5WOKwH3QoWk=,tag:vBG61XNnAbCghuf454Lujw==,type:str]
node_agent_dockhand_token: ENC[AES256_GCM,data:yS9PHeMLVq4=,iv:ck2JvhBw0soAvnIVj4KyR27HnqkD8RGBbHU8/Y9qxcI=,tag:wy6zmchdG+a4rQnWQpCDBA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhb0VmTW5rTGZxTi9JYmhU
            OXJNN01YWFFxMFFjWU0yYUcrZ2FoTGZZT3pzCnZ1K1ZvdXFIUmovR3QvWStjS2Fi
            S3c3cWZFM3hBaENyQ29hTHFjVGc3TncKLS0tIDAra2NPYytwM29NVk1ORFRxTCtP
            M2J1Q3lhOFUxZnpMdk1FREJPWW9SVDQKZHYh04GC4J9Vu66DghPhslg2Cb9TzKZM
            QtFRYaaJIk3hFVz7a8EExo/7d1ReDro09m+UboveKB9YUQFRyznHXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-23T10:42:57Z"
    mac: ENC[AES256_GCM,data:KJQBJqKGxKa00hce04An145YPI+btNFZpheD0umXNSLLOfshntMrm4G876fSoQehqdValUrOnQ+8Jj7sQPittRwY+OvSW6J9LEYrgoFGbIJ6FFhjrMggUW5PuKbtMsPyfvPq/CNxEHrsIXXS4ew3uJCIJUXuIJ8UeXOAj3RPhsc=,iv:mqBfJXoVy+jrifVio2SVZlHpl9oYopZn1kXtas4EJ2s=,tag:5u+8jmFm4LWLxwvHQY44Xw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
