ansible_host: ENC[AES256_GCM,data:F4GFSwR7uClOU8I=,iv:WPbnZ+Z9fglOr2gGwfWx9YKNxeSOf9yeSLVNr4mO6yY=,tag:+IQLlnAaSaMYz+AZWSiZNg==,type:str]
ansible_user: ENC[AES256_GCM,data:2OscVWE=,iv:2KUMnjazrSv7tnHX18iCkx9Cbz3spHR9yFBdXBPfLLU=,tag:1L3DWaXbwR7XBWA25Ybvtg==,type:str]
node_agent_obs_host: ENC[AES256_GCM,data:wsg/Ff0XDP4=,iv:TSAF03/iykfBTOHtG/STjbH8VpEkX5LcRJ5TxiWHTwU=,tag:iZqBpfj5qCR9LYOAKgtzZQ==,type:str]
node_agent_dockhand_url: ENC[AES256_GCM,data:NcdhwIAleZMvenYeax7pOw6Cev2Ya2tCpXgh/g9nbLv9/zGXfEN9Ng==,iv:Lt9UJoO0CDjEYdNevw7ImR5C3hdBbqOw0oI1rAqUBJ4=,tag:NUtxxplkFww0p7ZMkycplg==,type:str]
node_agent_dockhand_token: ENC[AES256_GCM,data:UX7jA9BICxo0dyTs7DJk95J0conMbU66Fxs3z68Wm1ohI0BYFaROW6PIpw==,iv:mK1X8CyQZcl/iongzonfGzbGzofHrp0PAFREfQiM8hY=,tag:imDI4Zo01N5C809RJnsJcQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiL2FQT2pVem5ISm1oSVEz
            VHZPNE5yZnRjdWFHQSthbHhJR051Z0M2Q25VCmJOZlBKd0VnRVlKS1NDbDBaMU9Y
            bzc0bVMwejdva0l2MDNwUFgrTjRtazgKLS0tIHlWL0svQjQ1T3VMbSt5WUhKajIw
            WVp2NTM5andCSDdBc01wVURtZEUzdmMKvvl+JLbWL1pl+f9jLD5fiQN8L3O5ZZmg
            2yhveTqP3Z7dicevhNO0IwaxbuNMNqEYb6IUCV7K3ADJdiFzieFllg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-23T10:09:55Z"
    mac: ENC[AES256_GCM,data:d4PdLKiJwMfFt63UW8l28F2Uq/o6GGEgknnQe+17FOACT6F+2uOcqtusVEzqHGeWYm+MfZW4B89HDVdInkhsURNasr767/QRWmR+kobjzaaYxefwn8PMz2q2frZlckpMeu3szauVSojbNNsVMt3pJimjeIyhYiSsMAQFLLvttkY=,iv:jQaztu5rfe/U3K6OKDwNWJD2n11mSEpP+mTgK8yKeSg=,tag:QjV0CIu/fKDime0bCs6iBA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
