ansible_host: ENC[AES256_GCM,data:Wt+zXpArMWmttp8=,iv:t0b4oyTUF70L9nW6YfjIVV6+P1FlFP0UKqCEIDOdlUY=,tag:ad6spKmTczxAGWG3bsT5Rw==,type:str]
ansible_user: ENC[AES256_GCM,data:3wKL/5o=,iv:4RXYFAnNB2f/fuUuSUKNp36KzDJ7+PSTIgEtXi2ytCg=,tag:6ZTVRyHGcROhDsDcJ8+eNQ==,type:str]
node_agent_obs_host: ENC[AES256_GCM,data:Li8VUB0MRgo=,iv:LiIyfuLZO1uH8sbfNlREBzS+IVxnFyGV11qSujM7LVI=,tag:YHbaKkEHGU60qBmONQISDw==,type:str]
node_agent_dockhand_url: ENC[AES256_GCM,data:sdidYhMJ1I6T1SzDTu0DmeDHaaA=,iv:Q44mcjL0dSYQ8QjrrhBF5STR4P/E7rzBUoSSAdXLZVA=,tag:W5eyrrqajKk4jBufQoKdvA==,type:str]
node_agent_dockhand_token: ENC[AES256_GCM,data:MYIuMPCR4io=,iv:4npjBsCCTLz2LxjPlvvjl7QzmSyttCOnBxmEnOwrDDg=,tag:xAkhm5eoO2+n16G/4bfrkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TFNVQ2o0YWJObHBGV3pH
            WWJhUUhYSnc0bkhwcTY5amVoU0pCaGw1YlFZClJrSTdUTFcwWUlMVlR6eXJlMnpN
            aHI1a2VjdVlTbG12c2ZBU0RKeVdmaEEKLS0tIEUwc2pKZGhqT2t4RHBYMXpFZHA5
            TGhLREJUUkVMZ1M0T0xaR2VEYzNjcDQKM70w/YyXPQoIIoARPcKNneBqZ5BL6/q5
            pscZ+OqnykxLInU7C3SCYex9EgEQglLo5Wvru0kcXUn33XpKnq5FVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-23T08:49:19Z"
    mac: ENC[AES256_GCM,data:/GOCZt0IPc39UtKBLz6xNxER9gjxBEsX72kDkoU5jljuOVLq+qRQFsloqbw162Fptgm2amMwd2Yk0O9NIkw9vr9Z4iZem9RxNG2KcgRakc478W44/7XPKf6vlQ2Fqas3WPXnPfqE9PbTVSHVyww3keaqN0QKzlCRxZCpIsDJVwA=,iv:X0gk9F+2kjjpEF/puuJ9LSlVnMIS28oKgYoR/l1jkcs=,tag:rO/9OFXCZcJJPQF+QNAhKQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
