- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  become: true

- name: Update /etc/hosts with hostname
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1\t{{ inventory_hostname }}"
  become: true
