ansible_host: ENC[AES256_GCM,data:gbO+lwF/48AcoOI=,iv:HENANFIDvh/4BZnF0Dw+qTaqKYxmNjgb8dAESz4fCEI=,tag:WAEZ5vmVxCpZRDQ0mZVZMw==,type:str]
ansible_user: ENC[AES256_GCM,data:6jkQizg=,iv:vHe97sEYI+Njsal3OaYUP6cEL+YKzHwtUzj68jc/uhg=,tag:86rmaooxTsusK70C0WsiMA==,type:str]
node_agent_obs_host: ENC[AES256_GCM,data:0b/jGDsDK4g=,iv:ouNav7ZB65MUlMPc7llkcHR9xUW0wDO5JjKwz6l7zVQ=,tag:33C2LNVvkCUeMAfHo2lCIA==,type:str]
node_agent_dockhand_url: ENC[AES256_GCM,data:/gQnmThBGWH22sMClIcmQnITBNY=,iv:ZCsRrtTjmsFHFnXNTsrtI8569NpijdsB4Odsxjsc36I=,tag:0YBngPEpAd2eLTiNJwVNmg==,type:str]
node_agent_dockhand_token: ENC[AES256_GCM,data:+WXs5guX+2c=,iv:A4KaKRF1rr3uTWlKcxBmzzrU+SQOo6VcuHfRn/v+Cfw=,tag:VK5NGooo5xjv18xR28zNug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDdHc2NkNueXhJQjlwMTJH
            aHZlODkvdWxwUlNPUC9UV3V3UVVoczFWV1hnCkZNVldsM1FvYmVhbmxrbjZNYTNk
            ZzBwSEwxcGNEVkU1ODhZdisvU1greFkKLS0tIEpCMXNBUWNkNjh2OHY0SHg0YS9Y
            ZElNaEkvbHlwdUZvYTBGdkx2NmJCR2cK3OWCRkBDaTmxP0w7p88MxH3T+vbxs9Ak
            hZBnwYldSiEZTjdIHcXQQNcgWmq3HQxheo5b2uoiyK23HuYBA/Bkzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-23T12:09:09Z"
    mac: ENC[AES256_GCM,data:PjARkM61dquvC2vFDGV8LXE89vtbKgtjjCBglAwpsPXMa2Z6I9MkSjEoJWYX97KVuMX8g8gdmFKTO5zP9huVyHSTM02DHkcx3srL7g79m/dkFNqtjN4XOdeYmDrIz55Eg5sp3Fi2kLf9id18FQHxFHSER46yvTQHoruc2OAGZc4=,iv:4hs5bm4iHZ06Hs0NJE793o14tb/Oyrk0Mc9BdxZDaXs=,tag:Amq0PUowb0+GpzzAcQH9Wg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
