ansible_host: ENC[AES256_GCM,data:3wK9NBYHH+KeMAk=,iv:b8L34OYPiXUy9qkFkZNhvZvpIqr9ZI1gTjUAB1ak00A=,tag:+qy1plva9T9QUJrV+sc/eQ==,type:str]
ansible_user: ENC[AES256_GCM,data:6di1pW0=,iv:n9HHu64DdMozhouMmAOzOZ2Z4PdIhh0ulsDE7WAE4AQ=,tag:MQr4YmrnI0MYN1604Tt2jQ==,type:str]
node_agent_obs_host: ENC[AES256_GCM,data:ozc/9NLb4cc=,iv:h4opqRDbRCjKakyMRxtPdLBRA4sW5Hj6v2X91ayjRJ0=,tag:qfqNNNT5090KJr1m7olZpg==,type:str]
node_agent_dockhand_url: ENC[AES256_GCM,data:FY9qbE7bHnlLn9kJl0CGEMspmvH61KE+0gp+U65K1j29OA7mGh5gOg==,iv:oh3uJ5G6veXH/zBvalKhpcFJ/r4lLKGPjTMnF4c+7Tg=,tag:989RPJcmlCWA1Xhumlo+xg==,type:str]
node_agent_dockhand_token: ENC[AES256_GCM,data:MGzlRoEsjnQ2B74SvZiq9/yVe4X0/Ull3GKgOwB2JaUwuAxU4exFZXyLVg==,iv:1EnMZHwKs4aR1G1HC3PwcQEOTfORbqpjk1xOadhCLBU=,tag:PY0LCmLQAq0EJ/O4SOMqaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZFg5VHhBSEF5MXJnc3dy
            Mi9OdmUrdWxzYjZ5aW5ISmlLcHE4NURWVkR3CkdJa2E0ZEI4d0dQaDNFUUd6Q0xE
            QXpLU3V2S2NGRHh2N1dhMEtwQmdJK0UKLS0tIGRCRFpub0tFdGJ3MGsrb08wa2Iv
            QUlEL3FRMlN3K2gzS2xTL0cwR2ZVelEKpkqkouBFIN4sCNuH8wIACMKjfE1sm13o
            6KWDwh10hzW110vKwUMwKlGvrABK3CFzYPO3RoWevw7UlyeaUoGpkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-23T09:38:20Z"
    mac: ENC[AES256_GCM,data:S5GmWTXI4kB3NUyfgdvJA+ssJqZeCxtsiQ6P+bg7HRIqKwEcIifJHJ07KrRbzrlIIhINGKh6Nk3UB+2PG2k/2nWGVyweGnSekVRxkoMsVXvzhSkhhFcYkoWVmjQwQdJ3HCuwT5NEuMV1iS4OzclMe4G6fvwGvSxNkffLQkqfiu0=,iv:vPSC7tkOW7ahAa7W2/8aHtyJCFLnkh/770mdyj8EEuQ=,tag:nlpoNLJTDiRX22pUUgxRIw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
